#pragma once
#include "altv-cpp-api/SDK.h"
#include "types.h"

extern "C"
{
    EXPORT uint16_t Vehicle_GetID(alt::IVehicle* vehicle); // optimization so the Vehicle_GetEntity isn't needed to retrieve the id
    EXPORT alt::IEntity* Vehicle_GetEntity(alt::IVehicle* player);

    EXPORT uint16_t Vehicle_GetGear(alt::IVehicle* vehicle);
    EXPORT void Vehicle_SetGear(alt::IVehicle* vehicle, uint16_t value);
    // todo handling
    EXPORT uint8_t Vehicle_GetIndicatorLights(alt::IVehicle* vehicle);
    EXPORT void Vehicle_SetIndicatorLights(alt::IVehicle* vehicle, uint8_t value);
    EXPORT uint16_t Vehicle_GetMaxGear(alt::IVehicle* vehicle);
    EXPORT void Vehicle_SetMaxGear(alt::IVehicle* vehicle, uint16_t value);
    EXPORT float Vehicle_GetRPM(alt::IVehicle* vehicle);
    EXPORT uint8_t Vehicle_GetSeatCount(alt::IVehicle* vehicle);
    EXPORT float Vehicle_GetWheelSpeed(alt::IVehicle* vehicle);
    EXPORT void Vehicle_GetSpeedVector(alt::IVehicle* vehicle, vector3_t& vector);
    EXPORT uint8_t Vehicle_GetWheelsCount(alt::IVehicle* vehicle);

    EXPORT uint8_t Vehicle_Handling_GetByModelHash(alt::ICore* core, uint32_t modelHash, alt::IHandlingData*& handling);
    EXPORT void Vehicle_GetHandling(alt::IVehicle* vehicle, alt::IHandlingData*& handling);
    EXPORT void Vehicle_ReplaceHandling(alt::IVehicle* vehicle);
    EXPORT void Vehicle_ResetHandling(alt::IVehicle* vehicle);
    EXPORT uint8_t Vehicle_IsHandlingModified(alt::IVehicle* vehicle);

    EXPORT uint32_t Vehicle_Handling_GetHandlingNameHash(alt::IHandlingData* handling);
    EXPORT float Vehicle_Handling_GetMass(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetMass(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetInitialDragCoeff(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetInitialDragCoeff(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetDownforceModifier(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetDownforceModifier(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetunkFloat1(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetunkFloat1(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetunkFloat2(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetunkFloat2(alt::IHandlingData* handling, float value);
    EXPORT void Vehicle_Handling_GetCentreOfMassOffset(alt::IHandlingData* handling, vector3_t& offset);
    EXPORT void Vehicle_Handling_SetCentreOfMassOffset(alt::IHandlingData* handling, vector3_t value);
    EXPORT void Vehicle_Handling_GetInertiaMultiplier(alt::IHandlingData* handling, vector3_t& offset);
    EXPORT void Vehicle_Handling_SetInertiaMultiplier(alt::IHandlingData* handling, vector3_t value);
    EXPORT float Vehicle_Handling_GetPercentSubmerged(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetPercentSubmerged(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetPercentSubmergedRatio(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetPercentSubmergedRatio(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetDriveBiasFront(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetDriveBiasFront(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetAcceleration(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetAcceleration(alt::IHandlingData* handling, float value);
    EXPORT uint32_t Vehicle_Handling_GetInitialDriveGears(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetInitialDriveGears(alt::IHandlingData* handling, uint32_t value);
    EXPORT float Vehicle_Handling_GetDriveInertia(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetDriveInertia(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetClutchChangeRateScaleUpShift(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetClutchChangeRateScaleUpShift(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetClutchChangeRateScaleDownShift(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetClutchChangeRateScaleDownShift(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetInitialDriveForce(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetInitialDriveForce(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetDriveMaxFlatVel(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetDriveMaxFlatVel(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetInitialDriveMaxFlatVel(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetInitialDriveMaxFlatVel(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetBrakeForce(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetBrakeForce(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetunkFloat4(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetunkFloat4(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetBrakeBiasFront(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetBrakeBiasFront(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetBrakeBiasRear(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetBrakeBiasRear(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetHandBrakeForce(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetHandBrakeForce(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSteeringLock(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSteeringLock(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSteeringLockRatio(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSteeringLockRatio(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionCurveMax(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionCurveMax(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionCurveMaxRatio(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionCurveMaxRatio(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionCurveMin(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionCurveMin(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionCurveMinRatio(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionCurveMinRatio(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionCurveLateral(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionCurveLateral(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionCurveLateralRatio(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionCurveLateralRatio(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionSpringDeltaMax(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionSpringDeltaMax(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionSpringDeltaMaxRatio(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionSpringDeltaMaxRatio(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetLowSpeedTractionLossMult(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetLowSpeedTractionLossMult(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetCamberStiffness(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetCamberStiffness(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionBiasFront(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionBiasFront(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionBiasRear(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionBiasRear(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetTractionLossMult(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetTractionLossMult(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSuspensionForce(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSuspensionForce(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSuspensionCompDamp(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSuspensionCompDamp(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSuspensionReboundDamp(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSuspensionReboundDamp(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSuspensionUpperLimit(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSuspensionUpperLimit(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSuspensionLowerLimit(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSuspensionLowerLimit(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSuspensionRaise(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSuspensionRaise(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSuspensionBiasFront(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSuspensionBiasFront(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSuspensionBiasRear(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSuspensionBiasRear(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetAntiRollBarForce(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetAntiRollBarForce(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetAntiRollBarBiasFront(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetAntiRollBarBiasFront(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetAntiRollBarBiasRear(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetAntiRollBarBiasRear(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetRollCentreHeightFront(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetRollCentreHeightFront(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetRollCentreHeightRear(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetRollCentreHeightRear(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetCollisionDamageMult(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetCollisionDamageMult(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetWeaponDamageMult(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetWeaponDamageMult(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetDeformationDamageMult(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetDeformationDamageMult(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetEngineDamageMult(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetEngineDamageMult(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetPetrolTankVolume(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetPetrolTankVolume(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetOilVolume(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetOilVolume(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetunkFloat5(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetunkFloat5(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSeatOffsetDistX(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSeatOffsetDistX(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSeatOffsetDistY(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSeatOffsetDistY(alt::IHandlingData* handling, float value);
    EXPORT float Vehicle_Handling_GetSeatOffsetDistZ(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetSeatOffsetDistZ(alt::IHandlingData* handling, float value);
    EXPORT uint32_t Vehicle_Handling_GetMonetaryValue(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetMonetaryValue(alt::IHandlingData* handling, uint32_t value);
    EXPORT uint32_t Vehicle_Handling_GetModelFlags(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetModelFlags(alt::IHandlingData* handling, uint32_t value);
    EXPORT uint32_t Vehicle_Handling_GetHandlingFlags(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetHandlingFlags(alt::IHandlingData* handling, uint32_t value);
    EXPORT uint32_t Vehicle_Handling_GetDamageFlags(alt::IHandlingData* handling);
    EXPORT void Vehicle_Handling_SetDamageFlags(alt::IHandlingData* handling, uint32_t value);
}