namespace AltV.Net.Enums
{
    public enum VehicleModType : byte
    {
        Spoilers,
        FrontBumper,
        RearBumper,
        SideSkirt,
        Exhaust,
        Frame,
        Grille,
        Hood,
        Fender,
        RightFender,
        Roof,
        Engine,
        Brakes,
        Transmission,
        Horns,
        Suspension,
        Armor,
        Turbo = 18,
        Xenon = 22,
        FrontWheels,
        BackWheels,
        PlateHolders,
        TrimDesign = 27,
        Ornaments,
        DialDesign = 30,
        SteeringWheel = 33,
        ShiftLever,
        Plaques,
        Hydraulics = 38,
        Boost = 40,
        WindowTint = 46,
        Livery = 48,
        Plate = 62,
        Color1 = 66,
        Color 2
    }
}